# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from typing import Any
import argparse
import io
import os
import subprocess
import sys
import traceback

BASE_DIR = parent
def run_transcription_standalone() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import traceback
import argparse
import subprocess
import datetime
import ntpath
import io
import core
import core.orchestrator
import config
import config.persistence